name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: 
      - dev
      - future
    tags:
      - v[0-9]+.[0-9]+.[0-9]+ # Matches all semantic versioning tags with major, minor, patch
  pull_request:
    branches: 
      - dev
      - future
      
env:
  MORYX_OPTIMIZE_CODE: "false"
  MORYX_BUILD_CONFIG: "Release"
  MORYX_BUILDNUMBER: ${{github.run_number}}
  dotnet_sdk_version: '7.x'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  REPOSITORY_NAME: ${{ github.event.repository.name }}

jobs:
  Build:
    uses: PHOENIXCONTACT/tools/.github/workflows/build-tool.yml@release-6
    with:
      MORYX_OPTIMIZE_CODE: "false"
      MORYX_BUILD_CONFIG: "Release"
      MORYX_BUILDNUMBER: ${{github.run_number}}
      dotnet_sdk_version: '7.x'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      REPOSITORY_NAME: ${{ github.event.repository.name }}

  UnitTests:
    needs: [Build]
    uses: PHOENIXCONTACT/tools/.github/workflows/unittest-tool.yml@release-6
    with:
      MORYX_OPTIMIZE_CODE: "false"
      MORYX_BUILD_CONFIG: "Release"
      MORYX_BUILDNUMBER: ${{github.run_number}}
      dotnet_sdk_version: '7.x'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      REPOSITORY_NAME: ${{ github.event.repository.name }}

  IntegrationTests:
    needs: [Build]
    uses: PHOENIXCONTACT/tools/.github/workflows/integrationtest-tool.yml@release-6
    with:
      MORYX_OPTIMIZE_CODE: "false"
      MORYX_BUILD_CONFIG: "Release"
      MORYX_BUILDNUMBER: ${{github.run_number}}
      dotnet_sdk_version: '7.x'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      REPOSITORY_NAME: ${{ github.event.repository.name }}

  ReportGenerator:
    needs: [UnitTests, IntegrationTests]
    uses: PHOENIXCONTACT/tools/.github/workflows/reportgenerator-tool.yml@release-6
    with:
      MORYX_OPTIMIZE_CODE: "false"
      MORYX_BUILD_CONFIG: "Release"
      MORYX_BUILDNUMBER: ${{github.run_number}}
      dotnet_sdk_version: '7.x'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      REPOSITORY_NAME: ${{ github.event.repository.name }}
               
  Publish-Test-Coverage:
    needs: [ReportGenerator]
    uses: PHOENIXCONTACT/tools/.github/workflows/publish-test-coverage-tool.yml@release-6
    with:
      MORYX_OPTIMIZE_CODE: "false"
      MORYX_BUILD_CONFIG: "Release"
      MORYX_BUILDNUMBER: ${{github.run_number}}
      dotnet_sdk_version: '7.x'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      REPOSITORY_NAME: ${{ github.event.repository.name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Documentation:
    needs: [UnitTests]
    uses: PHOENIXCONTACT/tools/.github/workflows/documentation-tool.yml@release-6
    with:
      MORYX_OPTIMIZE_CODE: "false"
      MORYX_BUILD_CONFIG: "Release"
      MORYX_BUILDNUMBER: ${{github.run_number}}
      dotnet_sdk_version: '7.x'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      REPOSITORY_NAME: ${{ github.event.repository.name }}

  Publish:
    needs: [UnitTests]
    uses: PHOENIXCONTACT/tools/.github/workflows/publish-tool.yml@release-6
    with:
      MORYX_OPTIMIZE_CODE: "false"
      MORYX_BUILD_CONFIG: "Release"
      MORYX_BUILDNUMBER: ${{github.run_number}}
      dotnet_sdk_version: '7.x'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      REPOSITORY_NAME: ${{ github.event.repository.name }}
    secrets: 
      MYGET_TOKEN: ${{secrets.MYGET_TOKEN}}
      NUGET_TOKEN: ${{secrets.NUGET_TOKEN}}
